# Generated by Django 5.1.1 on 2024-10-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movproduct',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='movproduct',
            name='from_dep',
            field=models.CharField(default='', max_length=10, verbose_name='Откуда'),
        ),
        migrations.AddField(
            model_name='movproduct',
            name='to_dep',
            field=models.CharField(default='', max_length=10, verbose_name='Куда'),
        ),
    ]
