# Generated by Django 5.1.1 on 2024-10-17 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('dep', models.CharField(choices=[('Сервис', 'Сервис'), ('Молл', 'Молл'), ('Плазма', 'Плазма'), ('Нагорное', 'Нагорное')], max_length=10, verbose_name='Отдел')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Задание')),
                ('assigned_to', models.CharField(max_length=20, verbose_name='Исполнитель')),
                ('completed', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.checklist')),
            ],
        ),
    ]
